# Generated by Django 4.0.1 on 2022-03-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_options_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articlesomid', to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
